version: '3.8'

services:
  backend:
    build: ./backend
    command: sh -c "uvicorn app.main:app --host 0.0.0.0 --reload --port 8080"
    ports:
      - "8080:8080"
    volumes:
      - ./backend:/app
      - ./backend/.env:/app/.env
    networks:
      - partymodelnet3

  db:
    image: postgres:16
    volumes:
      - ./db-data:/var/lib/postgresql/data
      - ./staticData:/staticData
    environment:
      POSTGRES_DB: myapp
      POSTGRES_USER: spa
      POSTGRES_PASSWORD: spa
    networks:
      - partymodelnet3
    ports:
      - "5432:5432"

  frontend:
    build: ./frontend
    command: npm run dev -- --host 0.0.0.0 --port 5173
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - backend
    networks:
      - partymodelnet3

networks:
  partymodelnet3:
    driver: bridge